# ALL
EXPORT_VARIABLES += $(EXPORT_ALL)
# 目标架构信息
EXPORT_CXX_MACROS += TARGET_ARCH_IS_$(TARGET_ARCH)

# 用户空间程序存放的位置
EXPORT_CXX_MACROS += USER_SPACE_START USER_SPACE_SIZE

# 内存信息
EXPORT_CXX_MACROS += RAM_START RAM_SIZE

# 内核起始地址
EXPORT_CXX_MACROS += KERNEL_ADDRESS

# 导出外设相关的信息
EXPORT_CXX_MACROS += PERIPHBASE PERIPHSIZE UART_BASE VIRTIO_0_BASE