# ALL
EXPORT_LINKER_SYMBOLS += $(EXPORT_ALL)

# elf相关
EXPORT_LINKER_SYMBOLS += IMAGE_BASE KERNEL_OFFSET 

# 导出内存布局参数
EXPORT_LINKER_SYMBOLS += DTB_SIZE STACK_SIZE CODE_SIZE USER_SPACE_SIZE VIDEO_RAM_SIZE RAM_START RAM_SIZE