# ONESHELL对于生成文件而言是重要的
.ONESHELL:

#重新定义clean
.PHONY:$(USER_CLEAN)
$(USER_CLEAN):clean
	- $(RM)  $(CLEAN-ALL-LIST)

# 定义生成的纯二进制文件,ELF和BINARY格式需要，否则ELF格式文件可能被当成中间文件而删除
# USER_ALL 已由单个生成文件代替
#.PHONY:$(USER_ALL)
#$(USER_ALL):$(MASTERY_GEN)



-include ../makefiles/makefile.$(TARGET_ARCH).targets
-include ../makefiles/makefile.auxfiles
-include ../makefiles/makefile.auxtargets
