# ONESHELL对于生成文件而言是重要的
.ONESHELL:

#重新定义clean
.PHONY:$(USER_CLEAN)
$(USER_CLEAN):clean
	- $(RM)  $(CLEAN-ALL-LIST)

# 定义生成的纯二进制文件,ELF和BINARY格式需要，否则ELF格式文件可能被当成中间文件而删除
.PHONY:$(USER_ALL)
$(USER_ALL):$(MASTERY_BINARY_BINARY) $(MASTERY_ELF_BINARY)
$(MASTERY_BINARY_BINARY):$(MASTERY_ELF_BINARY)
	$(TOOLCHAIN_OBJCOPY) -O binary $< $@

-include ../makefile.auxfiles
-include ../makefile.auxtargets
include ../makefile.$(TARGET_ARCH).targets
