/*
 * ByteReader.h
 *
 *  Created on: Feb 2, 2018
 *      Author: 13774
 */

#ifndef INCLUDE_TEMPLATES_IMPLEMENTATION_IO_BYTEREADER_H_
#define INCLUDE_TEMPLATES_IMPLEMENTATION_IO_BYTEREADER_H_


#endif /* INCLUDE_TEMPLATES_IMPLEMENTATION_IO_SectorReaderToByteReader_H_ */
