#QEMU_ROOT := 
QEMU_AARCH64 := $(QEMU_ROOT)/qemu-system-aarch64
PYTHON3 := /usr/bin/python3
DTC := /cygdrive/d/installed/githubs/dtc-for-win/dtc.exe
	
gdb_connect:
	$(GDB_BIN) -iex 'set disassemble-next-line on' -iex 'file $(MASTERY_ELF)' -iex 'target remote localhost:1234' -iex 'b *main' $(GDB_CONNECT_OPTIONS)
	

.PHONY:qemu_log
qemu_log:
	less qemu_log.txt