################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/arch/common_aarch64/exception \
src/arch/common_aarch64/mmu \
src/arch/host \
src/arch/qemu_virt \
src/arch/raspi3 \
src/arch/user_space \
src/data_structures \
src/filesystem/fat \
src \
src/io \
src/memory \
src/minimal_cpprt \
src/minimal_crt \
src/minimal_crt/stolen_from_libgcc \
src/schedule \
src/test \
subprojects/host/Debug \
subprojects/host/Debug/src/arch/common_aarch64/exception \
subprojects/host/Debug/src/arch/common_aarch64/mmu \
subprojects/host/Debug/src/arch/host \
subprojects/host/Debug/src/arch/qemu_virt \
subprojects/host/Debug/src/arch/user_space \
subprojects/host/Debug/src/data_structures \
subprojects/host/Debug/src/default_impl \
subprojects/host/Debug/src/filesystem/fat \
subprojects/host/Debug/src \
subprojects/host/Debug/src/io \
subprojects/host/Debug/src/memory \
subprojects/host/Debug/src/minimal_cpprt \
subprojects/host/Debug/src/minimal_crt \
subprojects/host/Debug/src/test \
subprojects/qemu_virt/Debug \
subprojects/qemu_virt/Debug/src/arch/common_aarch64/exception \
subprojects/qemu_virt/Debug/src/arch/common_aarch64/mmu \
subprojects/qemu_virt/Debug/src/arch/qemu_virt \
subprojects/qemu_virt/Debug/src/arch/user_space \
subprojects/qemu_virt/Debug/src/data_structures \
subprojects/qemu_virt/Debug/src/default_impl \
subprojects/qemu_virt/Debug/src/filesystem/fat \
subprojects/qemu_virt/Debug/src \
subprojects/qemu_virt/Debug/src/io \
subprojects/qemu_virt/Debug/src/memory \
subprojects/qemu_virt/Debug/src/minimal_cpprt \
subprojects/qemu_virt/Debug/src/minimal_crt \
subprojects/qemu_virt/Debug/src/test \
subprojects/raspi3/Debug \
subprojects/raspi3/Debug/src/arch/common_aarch64/exception \
subprojects/raspi3/Debug/src/arch/common_aarch64/mmu \
subprojects/raspi3/Debug/src/arch/qemu_virt \
subprojects/raspi3/Debug/src/arch/user_space \
subprojects/raspi3/Debug/src/data_structures \
subprojects/raspi3/Debug/src/default_impl \
subprojects/raspi3/Debug/src/filesystem/fat \
subprojects/raspi3/Debug/src \
subprojects/raspi3/Debug/src/io \
subprojects/raspi3/Debug/src/memory \
subprojects/raspi3/Debug/src/minimal_cpprt \
subprojects/raspi3/Debug/src/minimal_crt \
subprojects/raspi3/Debug/src/test \
subprojects/user_space/Debug \
subprojects/user_space/Debug/src/arch/common_aarch64/mmu \
subprojects/user_space/Debug/src/arch/user_space \
subprojects/user_space/Debug/src \
subprojects/user_space/Debug/src/io \
subprojects/user_space/Debug/src/memory \
subprojects/user_space/Debug/src/minimal_cpprt \
subprojects/user_space/Debug/src/minimal_crt \

