
# 布局相关
EXPORT_LINKER_SYMBOLS += USER_RAM_START USER_RAM_SIZE

# size参数
EXPORT_LINKER_SYMBOLS += USER_STACK_SIZE USER_CODE_SIZE USER_INITRAM_SIZE \
		USER_BSS_SIZE USER_DATA_SIZE

# start参数
EXPORT_LINKER_SYMBOLS += USER_STACK_START USER_CODE_START USER_INITRAM_START \
		USER_BSS_START USER_DATA_START