
# 目标架构信息
EXPORT_CXX_MACROS += TARGET_ARCH_IS_$(TARGET_ARCH)

# 用户空间程序存放的位置
EXPORT_CXX_MACROS += USER_SPACE_START USER_SPACE_SIZE

# 内存信息
EXPORT_CXX_MACROS += RAM_START RAM_SIZE

# 内核起始地址
EXPORT_CXX_MACROS += KERNEL_ADDRESS

# 导出外设相关的信息
EXPORT_CXX_MACROS += PERIPHBASE UART_BASE SDIO_0_BASE SDIO_1_BASE DDR_MEM_BASEADDR DDR_MEM_HIGHADDR