
# 根目录的所在的位置
EXPORT_VARIABELS += ROOT_PROJECT 

# 导出PATH
EXPORT_VARIABLES += PATH

# 导出与链接相关的
EXPORT_VARIABELS += USER_SPACE_START USER_SPACE_SIZE KERNEL_ADDRESS TARGET_ARCH MASTERY_ELF MASTERY_BINARY LINKER_SCRIPT

# 导出TOOLCHAIN 
EXPORT_VARIABELS += TOOLCHAIN_PREFIX TOOLCHAIN_CC TOOLCHAIN_CXX TOOLCHAIN_LD TOOLCHAIN_OBJCOPY TOOLCHAIN_OBJDUMP 

# 导出目标
EXPORT_VARIABELS += USER_ALL USER_CLEAN

# 导出构建系统的类型
EXPORT_VARIABELS += BUILD_BASE_SYSTEM BUILD_BASE_SYSTEM_IS_$(BUILD_BASE_SYSTEM)