# ALL
EXPORT_LINKER_SYMBOLS += $(EXPORT_ALL)

# elf相关
EXPORT_LINKER_SYMBOLS += IMAGE_BASE KERNEL_OFFSET 

# 导出内存布局参数
EXPORT_LINKER_SYMBOLS += DTB_SIZE STACK_SIZE CODE_SIZE INITRAM_SIZE      \
		 VIDEO_RAM_SIZE            \
		 RAM_START RAM_SIZE
# user
EXPORT_LINKER_SYMBOLS += USER_RAM_START USER_RAM_SIZE \
		USER_STACK_SIZE USER_CODE_SIZE USER_INITRAM_SIZE 