# DOCME 如何定义工程之间共享的变量
USER_RAM_START := 0x1000
USER_RAM_SIZE  := 0x1ff000 # DOCME 这里，0x200000应当是最后一个不可用的字节
USER_STACK_SIZE := 0x3000
USER_CODE_SIZE  := 0x20000
USER_INITRAM_SIZE := 0x1000
KERNEL_ADDRESS := $(shell echo "$$(($(RAM_START) + $(DTB_SIZE) + $(STACK_SIZE)))")
USER_SPACE_SIZE := $(shell echo "$$(($(USER_CODE_SIZE) + $(USER_INITRAM_SIZE)))")

EXPORT_ALL += USER_RAM_START USER_RAM_SIZE  USER_STACK_SIZE USER_CODE_SIZE \
	 USER_INITRAM_SIZE 